// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    return {
      book: require("text!templates/books/book.htm"),
      books: require("text!templates/books/booklist.htm"),
      layout: require("text!templates/books/layout.htm"),
      bookdetail: require("text!templates/books/bookdetail.htm")
    };
  });

}).call(this);
