// Generated by CoffeeScript 1.6.3
(function() {
  var API,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["msgbus", "marionette", "pages/book/list/controller"], function(msgBus, Marionette, Controller) {
    var Router, _ref;
    return Router = (function(_super) {
      __extends(Router, _super);

      function Router() {
        _ref = Router.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      return Router;

    })(Marionette.AppRouter);
  });

  ({
    appRoutes: {
      "": "defaultSearch",
      "search/:searchTerm": "search"
    }
  });

  API = {
    listCurrencies: function() {
      return Controller.listCurrencies();
    }
  };

  msgBus.commands.setHandler("ccys:route", function() {
    return new Router({
      controller: API
    });
  });

}).call(this);
